### ISSUE TITLE
filter nor-rec differences

### ISSUE THREAD

**Issue by j-budler** [geophysics-ubonn/reda#18]
If I have normal and reciprocal data, I want  to filter data which differ to much. Maybe there is already a  way to apply it, but I couldn't figure out, where the normal and where the reciprocal data points are stored.
Plots for the difference between normal and reciprocal would also be great.

**Comment by florian-wagner** [comment]
Yes, I agree, the data container should have a method like `ert.compute_reciprocal_error()`, which computes

![image](https://user-images.githubusercontent.com/2799008/33275699-bbfa4202-d393-11e7-82bc-80805a15d706.png)

and writes it to an appropriate column (`err`, `rec_err`?). Plotting could then be realized using the standard pseudosection plotting routines.

**Comment by florian-wagner** [comment]
P.S.: This get's interesting if one accounts for time-lapse errors https://doi.org/10.1190/geo2017-0024.1

**Comment by florian-wagner** [comment]
https://geophysics-ubonn.github.io/reda/documentation/api/reda.containers.html?highlight=recipro#reda.containers.ERT.ERT.compute_reciprocal_errors
