### ISSUE TITLE
automatic norrec assignment

### ISSUE THREAD

**Issue by j-budler** [geophysics-ubonn/reda#29]
The function reda.utils.norrec.assign_norrec_diffs(df, diff_list) needs the function reda.utils.norrec.assign_norrec_to_df to be executed before. But there is no reference to that in the description. An automatic execution of this function, if needed, but be even better.

**Comment by florian-wagner** [comment]
Yes, I agree that this was a bit cloudy. But the functions in `reda.utils.norrec` should be single-purpose functions to work with data frames in general. The ERT data container now holds a more convenient high-level method for the user:

``` python
# Make test data frame
import reda
ert = reda.ERT()
ert.data = reda.utils.norrec.get_test_df()

# Compute reciprocals
ert.compute_reciprocal_errors()
print(ert.data)
```
