### ISSUE TITLE
problems with: reda.utils.norrec.average_repetitions(df, keys_mean)

### ISSUE THREAD

**Issue by j-budler** [geophysics-ubonn/reda#30]
I thought, this function gives me the average of the normal and reciprocal measurement, but I seem to get only a rearranged data frame, sorted by the norrec ID. Also the output of this function changes, if the input data frame has an additional, but completely unrelated column.

**Comment by florian-wagner** [comment]
I cannot confirm this. The function does what it should do, average repititions. But you are right, the reordering of the columns is not necessary. I have fixed this.

Here is a minimal working example:

```python
import reda
data = reda.utils.norrec.get_test_df()
print(data)

reda.utils.norrec.assign_norrec_to_df(data)

print(data)
data = reda.utils.norrec.average_repetitions(data, keys_mean=["R"])

print(data)
```
