### ISSUE TITLE
Computation of K and rho_a with topography from a BERT file + ERT.assign_norrec error + error with pseudosections plotting

### ISSUE THREAD

**Issue by ThibaultMan** [geophysics-ubonn/reda#32]
Hi,
I have two questions : 
- If I want to import a .ohm file with BERT syntax, I don't have my K factor. Is REDA able to compute rho_a including the important micro-topography I have ?

- I have two error when I try to use your example with my files. WOuld you have some advices ??

"
#%% DATA FILTERING

#Data importation
path = "data"
files = [os.path.join('C:\BERT\Potential\Field\Inversion\data\Time-lapse irrigation', f) for f in os.listdir('C:\BERT\Potential\Field\Inversion\data\Time-lapse irrigation') if f.endswith(".ohm")]

files.sort()
print("Found %d files in %s: %s" % (len(files), path, files))

data = ERT()

for nr, filename in enumerate(files):
    data.import_bert(filename,timestep=13)
    
#Histogram plotting and filtering
import  reda.plotters.histograms as RH
results = RH.plot_histograms_extra_dims(
        data, keys = ['rho_a'], extra_dims =['timestep'], Nx=5, subquery='timestep in [1,2,3,4]')
"

Many thanks in advance,

Tibo

![reda_filtering](https://user-images.githubusercontent.com/37246575/41497824-d42d2f66-715d-11e8-8e83-4888110ac2d7.png)

**Comment by florian-wagner** [comment]
Hi @ThibaultMan,

for the first question: No, the correct geometric factors and the correct apparent resistivity needs a fine mesh to calculate the primary potentials. REDA handles data only and has no meshing or simulation functionality. So for this, you would have to use pybert.

I'll have a look at question 2 later today.

cheers
Florian

**Comment by florian-wagner** [comment]
Hi @ThibaultMan,

with regard to your second questions, can you try updating and see if the new `compute_reciprocal_errors` works for you?

https://geophysics-ubonn.github.io/reda/documentation/api/reda.containers.html?highlight=recipro#reda.containers.ERT.ERT.compute_reciprocal_errors

Best wishes
Florian
