### ISSUE TITLE
BaseContainer - discussion

### ISSUE THREAD

**Issue by j-gallistl** [geophysics-ubonn/reda#67]
To solve the container inheritance issues the use of a `BaseContainer` was suggested. It could incorporate a generalized `Importers` or `ImportersBase` class and a generalized `Exporters` class. All other classes `ERT` etc. inherit from that class. 

In such a way inheritance would be "more" logic and a lot of redundant code for the importers/exporters could be saved. 

What about the `LoggingClass`? Inheritance in the `BaseContainer` or in the specific ERT/SIP classes?

**Comment by m-weigand** [comment]
I think we need specialized importer classes that inherit vom ImportersBase, i.e. ImportersERT, ImportersTDIP, ImportersCR, ...
While at this point it seems that there is a lot of duplicated import/export code in the different container classes, I believe that this will not be the case once things are sorted out.

Regarding the logging class, this would go into the base container, as all containers require logging. At this point I'm not sure if we will need specilized logging facilities, i.e., for sEIT operations. However, in this case it will be easy to introduce LoggingsEIT

**Comment by florian-wagner** [comment]
I agree with both of you. A `BaseContainer` from which the `ERTContainer` and others are derived would be the first step and Importers could already be modified in these derivatives. `ERTImporters` is an additional level of granularity that I would consider to be a second step. 

BTW, @j-gallistl thanks for your contributions! That's great.

**Comment by m-weigand** [comment]
Closing as we had a BaseContainer class for some time now.
